export const componentCardDescriptions = {
  zh: {
    surfaces: "为浅色和深色模式提供五个语义表面，并按用途定义阴影层级。",
    "semantic-tokens": "颜色、表面、排版、形状与层级的完整运行时语义契约。",
    scrollbars: "始终可用又不过度干扰的滚动条；基于 shadcn 的滚动淡出方案重构，适配形状系统，并在触屏保留原生滚动。",
    motion: "供所有组件共享的弹簧令牌、更快退场与无重排字重动画规则。",
    "app-shell": "可组合的应用框架，用于容纳 Sidebar、Header 和主内容。",
    "page-layout": "用于组合可选页面信息、路由导航、内容区与辅助区域的响应式页面布局。",
    sidebar: "支持桌面端折叠与移动端抽屉的响应式导航栏。",
    "top-nav": "可组合的顶部导航，包含品牌、主链接与操作区。",
    "nav-menu": "供 Sidebar 与 TopNav 共享、与路由实现无关的导航基础组件。",
    accordion: "支持展开与收起动画的折叠区块；分组模式下提供邻近悬停反馈。",
    alert: "可组合的上下文提示，支持语义状态、可选图标、辅助说明与操作。",
    "inline-notice": "安静的行内强调提示，可与 Badge 组合，并支持语义强调变体。",
    badge: "紧凑标签，支持分类颜色、自定义配方、语义状态，以及柔和、高强调和圆点变体。",
    "badge-overflow": "响应式标签列表，会将隐藏项目收纳为溢出计数。",
    breadcrumb: "可组合的路径导航，支持分隔符、当前页状态与层级折叠。",
    button: "通用按钮，支持多种变体、尺寸、加载状态与图标。",
    "button-group": "将相关操作连接为紧凑的横向或纵向控件，支持分裂按钮、分隔符与上下文附加内容。",
    card: "基于 Zeron Design 重构的组合式卡片，支持堆叠、行内和网格布局、无边框分隔与二维邻近悬停。",
    container: "可组合的承载容器，可在浮动内容主体外添加可选的页头与页脚。",
    checkbox: "紧凑复选框，支持选中、半选、禁用、校验与表单状态。",
    "checkbox-group": "通过合并背景呈现连续选择状态的复选框组。",
    "color-picker": "支持 HEX、RGB、HSL、OKLCH、透明度、色板与弹出触发器的颜色选择器。",
    "data-grid": "虚拟化表格数据网格，支持行内编辑、范围选择、搜索、复制粘贴与固定列。",
    "data-table": "基于 TanStack 的数据表格，支持排序、筛选、分页、选择、列显隐与固定。",
    "detail-list": "带边框的标签—值列表，支持分组与分隔，适合紧凑呈现资源和实体详情。",
    "metric-card": "自适应单指标卡片，支持可选明细、趋势展示、数据状态与整卡交互。",
    dialog: "带平滑进出动画和遮罩层的模态对话框。",
    dropdown: "菜单式下拉组件，带邻近悬停和背景动画。",
    field: "无障碍表单组合，支持标签、说明、校验消息、分组与字段集。",
    input: "文本输入框，提供三种变体、五种尺寸与无障碍校验状态。",
    "input-copy": "只读输入框，提供复制按钮与动画反馈。",
    "input-group": "可组合输入组，支持附加内容、紧凑操作、文本域与校验。",
    "info-item": "可组合的信息行，支持前置媒体、主信息、辅助信息与灵活的末端数值或详情。",
    kbd: "用于键盘命令与交互提示的紧凑按键帽和快捷键组合。",
    popover: "具备碰撞规避能力的浮层，支持从锚点到面板的流畅过渡。",
    "radio-group": "支持表单使用的单选组，并提供增强的邻近悬停行。",
    separator: "带语义边框色和安全间距的无障碍水平与垂直分隔线。",
    select: "带动画的选择菜单，支持带边框、无边框变体与可选图标。",
    slider: "范围滑块，支持步进吸附、区间模式与动画滑块手柄。",
    "sortable-collection": "受控的可排序列表，支持行内编辑、移除和从目录添加项目。",
    stepper: "无障碍多步骤导航，支持校验、完成状态与键盘操作。",
    switch: "带动画滑块与标签的开关控件。",
    table: "具有行悬停反馈和语义化标记的数据表格。",
    tabs: "支持胶囊、分段和下划线样式，以及滑动激活指示器的标签页。",
    textarea: "多行文本输入，支持语义变体、两种内容尺寸、调整大小与字段校验。",
    toast: "支持状态、自动关闭、操作与拖拽手势的动画通知栈。",
    tooltip: "带弹簧动画和可配置位置的浮动提示。",
    "ask-user-questions": "分步提问流程，支持单选、多选、可选“其他”输入与跳过。",
    "chat-message": "带内置动效、用户与助手对齐方式及文件附件的聊天消息气泡。",
    "input-message": "聊天式消息编辑器，支持自适应高度文本域与可配置操作槽位。",
    "thinking-indicator": "带形变 SVG 与循环文案的动画状态指示器。",
    "thinking-steps": "按顺序展示并支持折叠的思考步骤组件。",
  },
} as const;

export function componentCardDescription(slug: string, language: "en" | "zh", fallback?: string) {
  return language === "zh" ? componentCardDescriptions.zh[slug as keyof typeof componentCardDescriptions.zh] ?? fallback : fallback;
}
