// Generated by scripts/generate-preview-sources.mjs. Do not edit.
import type { PreviewSourceReference } from "./preview-source";

const blockPreviewSources = {
  "transaction-details-01": {
    "url": "/docs-source/a6a5a5b658429ab4ee817c1407584edfb4cc298494a447495f89a46d00c1ef07.txt"
  },
  "cost-estimate-01": {
    "url": "/docs-source/28099758c9f88e15cf5bd3b576c0dd3710498405e31d594118d6c164ef391fc7.txt"
  },
  "getting-started-01": {
    "url": "/docs-source/aaedb2afa3857a884c90d9879ef7c9398544c8b8655fddcc15a792c0fc1b9a58.txt"
  },
  "security-overview-01": {
    "url": "/docs-source/4e3bb2f41fb4432d819e89cf31d4ae34bb7062df944157b3198779861486e95a.txt"
  },
  "deployment-detail-01": {
    "url": "/docs-source/26eb77f014d1af9956d1d9e07e42ab54413ba2f9d3583568019a66405c7a1bae.txt"
  },
  "project-monitor-01": {
    "url": "/docs-source/058c5fdea7607ef2ccd3c0b751cd69ebaf331c18ceabf63236f46ebf09831a2a.txt"
  },
  "agent-message-trace-01": {
    "url": "/docs-source/61a51108c5b81418fd886efa3b7c6813bc5ad04c9fc51a83c7f034e1ae45e14d.txt"
  },
  "agent-session-detail-01": {
    "url": "/docs-source/0113bb3386029f21c1066d82d73df30f94fc3bb6db5c087b7766fa3dca9367f8.txt"
  },
  "agent-trace-01": {
    "url": "/docs-source/651806a36c908eb7e9cc9e52f48dc28165dec4dcc46ef2866efada74aca3f089.txt"
  },
  "ai-gateway-overview-01": {
    "url": "/docs-source/a75dae796901f96e4ff236fa16d62f8a43b3bdf069776ebe037276528c6bb9a4.txt"
  },
  "ai-gateway-session-list-01": {
    "url": "/docs-source/bc4fd8c7093596da2df67e90f17d7f23d9878401fed64816d77786e95acffd0b.txt"
  },
  "availability-monitor-01": {
    "url": "/docs-source/4ff71655a784db3dd3cddf8da28ce0acdf0f312e0d45c2599b4852d7bc1c1cc8.txt"
  },
  "cluster-environment-detail-01": {
    "url": "/docs-source/16ff6ab83985547c95fc1ece28243431061b43c6331b076501e88aeb020f3ed1.txt"
  },
  "cluster-environment-list-01": {
    "url": "/docs-source/533e6f54c82ef98b17ca265bc5dde1ea177ceb936be13db45ad633e3ff438464.txt"
  },
  "model-router-01": {
    "url": "/docs-source/36e6f6c193edc8146cd880be9574e3cc769da24406220696e639d6d62f8851f7.txt"
  },
  "credit-usage-01": {
    "url": "/docs-source/f5c92e90e461bdf0e977f4449eb2a3b743f8c46f0f16bf2126507f6f329e4de2.txt"
  },
  "file-manager-01": {
    "url": "/docs-source/651e8c04677c7c74cfb396348128c900cded9e528e35f656928b5fdb3570f69a.txt"
  },
  "filter-rule-builder-01": {
    "url": "/docs-source/6345ad7fedbdbc1a7293f45c65e97d8761d1bf4fb80ec6dbe39bc1f2abc85af6.txt"
  },
  "infinite-log-table-01": {
    "url": "/docs-source/511a776133826a05726ba88970f93f985ae6b866fb2abae2ba2f01ff49d0d114.txt"
  },
  "inspection-report-list-01": {
    "url": "/docs-source/83340eaafd11e47a2772bd9d741377888e3c3a49505dc272a4d83ea9d7185e87.txt"
  },
  "login-01": {
    "url": "/docs-source/378be46e15e91313ebffafaa02f4c8743446eea80a9f43170230a68ea45ba4fa.txt"
  },
  "mcp-detail-01": {
    "url": "/docs-source/69ac76f465153ddf6dfae1844ed038423deb8f3fe78967724489f35a329fd959.txt"
  },
  "member-department-01": {
    "url": "/docs-source/eca3b203f1ad0358e9dd3debceea42a6255741d899aa76795499e05b6a19580e.txt"
  },
  "model-detail-01": {
    "url": "/docs-source/5d71ed4fdbf6bbc67732350640a2839cd6622918a9387e60772b80bd10e4ad13.txt"
  },
  "model-detail-02": {
    "url": "/docs-source/4d3c3b770f96af19f49327beedbdca301568e67233e35a03849865f854add2fa.txt"
  },
  "monitoring-alert-list-01": {
    "url": "/docs-source/a61e0289405db1bda1e4582b7e62533e9c50f7195d6282582bf620707a3e7267.txt"
  },
  "personal-model-usage-01": {
    "url": "/docs-source/d5ebf2785cfca9ca75d1d0c8f2c0199674644407d7b20e1d80853e0960361fdc.txt"
  },
  "personal-settings-01": {
    "url": "/docs-source/8e7fdc101eb9454081d3b2b8a0ef892f6f650dd4ef355d5c29afcd56902f7edb.txt"
  },
  "personal-usage-01": {
    "url": "/docs-source/5d4274f2e367a125cb5cc0c84079685e60db17bd9fcb588a0b98daff649b833e.txt"
  },
  "provider-create-form-01": {
    "url": "/docs-source/8bbdacc7ceaa6079add9d7b19c505b86021f1288da4d31f0541dbca35d1e3eaa.txt"
  },
  "resource-catalog-01": {
    "url": "/docs-source/c51c2552d5b5b687f757d05a3547ab81405ef88f94a356879c4c563c49230334.txt"
  },
  "resource-detail-page-01": {
    "url": "/docs-source/2651e6581095421a9d54eecca35cca2f0de14e10815249ce45d87516bb4393ff.txt"
  },
  "resource-list-page-01": {
    "url": "/docs-source/d26ab9e1c93d179d0a2d9d7320e18c9c73b96023d224213c07302c6a70e5c801.txt"
  },
  "resource-list-table-01": {
    "url": "/docs-source/52b653eee4ea92401bf8a60215af5f67517de53b5edbab870ce481cc8eece9f5.txt"
  },
  "resource-metric-list-01": {
    "url": "/docs-source/90ec460215f3cc00686a1b4e04264a661244a24de4a26bdbab8553e23d76c449.txt"
  },
  "resource-settings-01": {
    "url": "/docs-source/3c00722e88fbbd1baf500e66d94f087b20dbc7a19e1e5c2577fa4fd31510fdfc.txt"
  },
  "resource-status-all-01": {
    "url": "/docs-source/ee53e80e08bcf2fd7db78492358b639af8dd207f78c2b0ae2b63f2afda588bf4.txt"
  },
  "rule-flow-editor-01": {
    "url": "/docs-source/bccf1eaadc4af65cbad064d272b6b48f03287e22879112e45af5becb4f4ef548.txt"
  },
  "service-management-01": {
    "url": "/docs-source/ebb28c0a85a0939e139217d3317af44057ae0a3700dfadda1f7bc506e59232f2.txt"
  },
  "signup-01": {
    "url": "/docs-source/d39d22e4acbdaf223fc23b0acc5831eb9bb97bf09073fb150de2629fc11dddef.txt"
  },
  "storage-usage-01": {
    "url": "/docs-source/31fa27336b5e9c2918a3763b91bf337c3126bea4032644bf37410a1c5128f562.txt"
  },
  "traffic-rules-01": {
    "url": "/docs-source/b0b52c8cf9dda1b2208eebd3d3357a4a6c088565de13fd1f4246800c83330a20.txt"
  },
  "zlrlist": {
    "url": "/docs-source/e6b07997030af86298c5fa84e030455338f68e164ce091f634fc6eea2e3fc00c.txt"
  }
} as const satisfies Record<string, PreviewSourceReference>;

export function getBlockPreviewSource(slug: keyof typeof blockPreviewSources): PreviewSourceReference {
  return blockPreviewSources[slug];
}

/** Exact known assets only: missing hashes must never receive immutable caching. */
export function getPreviewSourceAssetUrls(): string[] {
  return [...new Set(Object.values(blockPreviewSources).map(({ url }) => url))];
}
