// Generated by scripts/generate-preview-sources.mjs. Do not edit.
import type { PreviewSourceReference } from "./preview-source";

const blockPreviewSources = {
  "website-analytics-01": {
    "url": "/docs-source/32d7db9240c837ba0cfa927b771846317c313d43054017d99415ed21fe287532.txt"
  },
  "sales-conversion-funnel-01": {
    "url": "/docs-source/125e7314d3a8047e6f83c43f7810ef333b5e06a4e8a99de3a341bce357604e9e.txt"
  },
  "design-stack-01": {
    "url": "/docs-source/4dd4976b8142e62722c36340b70c957aeb05c963063df86a15d89106dbf91f90.txt"
  },
  "file-upload-01": {
    "url": "/docs-source/115645f0ebf9b7ebdf43ed4654eec57632afbc054519bd35a6d1d04a51f37e9d.txt"
  },
  "support-analytics-01": {
    "url": "/docs-source/5a069fdea7c15322ebc00a234153ecc6bc3c9613c05d1d8ebfedc7668093a420.txt"
  },
  "transaction-details-01": {
    "url": "/docs-source/e3216c7b2751829596d61e32da13b51123b7aa17887bfbf788b003f36a12f353.txt"
  },
  "cost-estimate-01": {
    "url": "/docs-source/d30d26aa2e994f735fb3048ec081f3059ad77b6541440eedd4c5ec80384bf7f2.txt"
  },
  "getting-started-01": {
    "url": "/docs-source/aaedb2afa3857a884c90d9879ef7c9398544c8b8655fddcc15a792c0fc1b9a58.txt"
  },
  "integration-monitors-01": {
    "url": "/docs-source/e935ce781dadea500d68d9e0bac28246ea2961b4a94fe4d8be9dcf0e60840028.txt"
  },
  "security-overview-01": {
    "url": "/docs-source/30823fbbf08e635f17494f81cdd6ff5853a6b2128f109e8694dd7368482ffb3b.txt"
  },
  "deployment-detail-01": {
    "url": "/docs-source/8bea852e7f437aca1091bb56048873814f6f2434bebb29617c8797da6c93f8fd.txt"
  },
  "project-monitor-01": {
    "url": "/docs-source/4d09c7ba7a25973b56c6a12bb9c8e2a0a9385a3c5f4c4c8268b9019ecca5e844.txt"
  },
  "agent-message-trace-01": {
    "url": "/docs-source/61a51108c5b81418fd886efa3b7c6813bc5ad04c9fc51a83c7f034e1ae45e14d.txt"
  },
  "agent-session-detail-01": {
    "url": "/docs-source/0113bb3386029f21c1066d82d73df30f94fc3bb6db5c087b7766fa3dca9367f8.txt"
  },
  "agent-trace-01": {
    "url": "/docs-source/0fe9f53d9cb1abbda9a7fc355c5f23f350a98010dc5e8be5b96f9ab632e7ada3.txt"
  },
  "ai-gateway-overview-01": {
    "url": "/docs-source/a75dae796901f96e4ff236fa16d62f8a43b3bdf069776ebe037276528c6bb9a4.txt"
  },
  "ai-gateway-session-list-01": {
    "url": "/docs-source/e0489477ddb061c2fa66fbfc15f5a41310403a1766fb1fd9e5e69cab97b45aac.txt"
  },
  "cluster-environment-detail-01": {
    "url": "/docs-source/16ff6ab83985547c95fc1ece28243431061b43c6331b076501e88aeb020f3ed1.txt"
  },
  "cluster-environment-list-01": {
    "url": "/docs-source/533e6f54c82ef98b17ca265bc5dde1ea177ceb936be13db45ad633e3ff438464.txt"
  },
  "model-router-01": {
    "url": "/docs-source/b40014001850c5ff4e2ef3e56518751ba7e1ca8b6025994a7d7ccc5333a72e41.txt"
  },
  "credit-usage-01": {
    "url": "/docs-source/796b3f95668f0fb7661e29ab4a74597a967974bf0754e363b0e9fb08501fb62f.txt"
  },
  "file-manager-01": {
    "url": "/docs-source/f1d4694c301c959fd8cb0e8b3826fc4f062fafd90ce61158362b45ec97fa36a7.txt"
  },
  "filter-rule-builder-01": {
    "url": "/docs-source/6345ad7fedbdbc1a7293f45c65e97d8761d1bf4fb80ec6dbe39bc1f2abc85af6.txt"
  },
  "infinite-log-table-01": {
    "url": "/docs-source/511a776133826a05726ba88970f93f985ae6b866fb2abae2ba2f01ff49d0d114.txt"
  },
  "inspection-report-list-01": {
    "url": "/docs-source/83340eaafd11e47a2772bd9d741377888e3c3a49505dc272a4d83ea9d7185e87.txt"
  },
  "login-01": {
    "url": "/docs-source/3efbe0b184c7ee7ad5d8d4ca0cefcd4f9ed7f254267b187fa49f30b3bff31830.txt"
  },
  "mcp-detail-01": {
    "url": "/docs-source/69ac76f465153ddf6dfae1844ed038423deb8f3fe78967724489f35a329fd959.txt"
  },
  "member-department-01": {
    "url": "/docs-source/eca3b203f1ad0358e9dd3debceea42a6255741d899aa76795499e05b6a19580e.txt"
  },
  "model-detail-01": {
    "url": "/docs-source/5d71ed4fdbf6bbc67732350640a2839cd6622918a9387e60772b80bd10e4ad13.txt"
  },
  "model-detail-02": {
    "url": "/docs-source/63d8559ced99fde9cec0c77ef21ca8e8e7aa72bb00de62423f98e4439b991415.txt"
  },
  "monitoring-alert-list-01": {
    "url": "/docs-source/a61e0289405db1bda1e4582b7e62533e9c50f7195d6282582bf620707a3e7267.txt"
  },
  "personal-model-usage-01": {
    "url": "/docs-source/d5ebf2785cfca9ca75d1d0c8f2c0199674644407d7b20e1d80853e0960361fdc.txt"
  },
  "personal-settings-01": {
    "url": "/docs-source/def09d975f783f553372d7689eea7f9e61e4f43df61ba5b56ad5f2b580903a3f.txt"
  },
  "personal-usage-01": {
    "url": "/docs-source/5d4274f2e367a125cb5cc0c84079685e60db17bd9fcb588a0b98daff649b833e.txt"
  },
  "provider-create-form-01": {
    "url": "/docs-source/8bbdacc7ceaa6079add9d7b19c505b86021f1288da4d31f0541dbca35d1e3eaa.txt"
  },
  "resource-catalog-01": {
    "url": "/docs-source/c51c2552d5b5b687f757d05a3547ab81405ef88f94a356879c4c563c49230334.txt"
  },
  "resource-detail-page-01": {
    "url": "/docs-source/6d8b4c0c35d7064f637f67b39c39d63c5f09c9b4a031ec28bd37305cce45cd55.txt"
  },
  "resource-list-page-01": {
    "url": "/docs-source/d26ab9e1c93d179d0a2d9d7320e18c9c73b96023d224213c07302c6a70e5c801.txt"
  },
  "resource-list-table-01": {
    "url": "/docs-source/77c8fc99ea774be3050a39e228af2ac6feeebad20059aa57b8492eab03526f40.txt"
  },
  "resource-metric-list-01": {
    "url": "/docs-source/1f7bb72ce8204c8888883aced64553334a19376ec86aede0cee1a825eb063760.txt"
  },
  "resource-settings-01": {
    "url": "/docs-source/3c00722e88fbbd1baf500e66d94f087b20dbc7a19e1e5c2577fa4fd31510fdfc.txt"
  },
  "resource-status-all-01": {
    "url": "/docs-source/bed1aef6d518635a34bb8557e18c65f024cac25ca86658e705b7362a930550b7.txt"
  },
  "rule-flow-editor-01": {
    "url": "/docs-source/bccf1eaadc4af65cbad064d272b6b48f03287e22879112e45af5becb4f4ef548.txt"
  },
  "service-management-01": {
    "url": "/docs-source/ebb28c0a85a0939e139217d3317af44057ae0a3700dfadda1f7bc506e59232f2.txt"
  },
  "signup-01": {
    "url": "/docs-source/57ce10e8b50e55d75f8b106f75d4445faae315c74d0b6885649b97aa3503ddc3.txt"
  },
  "storage-usage-01": {
    "url": "/docs-source/28da1e74404e7dd71f617225ba95d2b2a612924cfc3e0763eedeeac131433b62.txt"
  },
  "traffic-rules-01": {
    "url": "/docs-source/b0b52c8cf9dda1b2208eebd3d3357a4a6c088565de13fd1f4246800c83330a20.txt"
  },
  "zlrlist": {
    "url": "/docs-source/e6b07997030af86298c5fa84e030455338f68e164ce091f634fc6eea2e3fc00c.txt"
  }
} as const satisfies Record<string, PreviewSourceReference>;

export function getBlockPreviewSource(slug: keyof typeof blockPreviewSources): PreviewSourceReference {
  return blockPreviewSources[slug];
}

/** Exact known assets only: missing hashes must never receive immutable caching. */
export function getPreviewSourceAssetUrls(): string[] {
  return [...new Set(Object.values(blockPreviewSources).map(({ url }) => url))];
}
