export type ComponentCoverTheme = "light" | "dark";

/**
 * Static captures of each component's canonical playground state. They are
 * generated by `pnpm covers:generate` and intentionally live in `public` so
 * the collection page never mounts documentation playgrounds inside cards.
 */
export function componentCoverSrc(slug: string, theme: ComponentCoverTheme) {
  return `/component-covers/${slug}-${theme}.jpg`;
}
