"use client";

import { useState } from "react";
import { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from "@zeron/ui/heatmap-chart";
import { Button } from "@zeron/ui/button";
import { ComponentPreview } from "@docs/components/content/ComponentPreview";
import { DocPage, DocSection } from "@docs/components/content/DocPage";
import { PropsTable } from "@docs/components/content/PropsTable";
import { ChartDataTable } from "@zeron/ui/chart-primitives";
import { useTranslations } from "next-intl";
import { Link } from "@/app/_i18n/navigation";

const rangeStart = new Date(2026, 0, 1);
const rangeEnd = new Date(2026, 11, 31);
const weekStart = getHeatmapWeekStartSunday(rangeStart);
const data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {
  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);
  return { bin: row, date, count: (column * 3 + row * 7) % 9 };
}) }));



function BasicDemo() { return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart><HeatmapLegend /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }

function QuartersDemo() { return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]} weekStartDay={1}><HeatmapCells rowOpacity={[1,1,1,1,1,0.6,0.6]} /><HeatmapSeparator groupBy="quarter" spacing={12} /><HeatmapXAxis /><HeatmapYAxis tickFilter="all" labelFormat="initial" /><HeatmapTooltip /></HeatmapChart><HeatmapLegend variant="gradient" /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }

function SizingDemo() { return <div className="w-full space-y-4"><div className="h-44"><HeatmapChart data={data.slice(0,26)} layout="fill"><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div><div className="overflow-x-auto"><HeatmapChart data={data.slice(0,12)} binSize={15}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div></div>; }

function PatternsDemo() { const styles = HEATMAP_DEFAULT_LEVEL_COLORS.map((color,index) => ({color,fillMode:index > 0 ? "pattern" : "solid",pattern:"diagonal"})) as unknown as HeatmapLevelStyles; return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]} levelStyles={styles}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart><HeatmapLegend levelStyles={styles} /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }

function RangeDemo() { const [half, setHalf] = useState(false); return <div className="w-full"><Button size="sm" variant="secondary" onClick={() => setHalf(v => !v)}>Toggle six months</Button><HeatmapChart data={data} xDomain={[rangeStart,half ? new Date(2026,5,30) : rangeEnd]} sizingColumnCount={half ? 27 : 53}><HeatmapCells hideGhostCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div>; }

function LoadingDemo() { const [loading, setLoading] = useState(false); const [replay, setReplay] = useState(0); return <div className="w-full"><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setLoading(v => !v)}>Toggle loading</Button><Button size="sm" variant="secondary" onClick={() => setReplay(v => v + 1)}>Replay</Button></div><HeatmapChart data={data} status={loading ? "loading" : "ready"} loadingLabel="Loading activity" revealSignature={String(replay)}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div>; }

const basicCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction BasicDemo() { return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart><HeatmapLegend /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }\n\nexport default function Example() { return <BasicDemo />; }\n";
const quartersCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction QuartersDemo() { return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]} weekStartDay={1}><HeatmapCells rowOpacity={[1,1,1,1,1,0.6,0.6]} /><HeatmapSeparator groupBy=\"quarter\" spacing={12} /><HeatmapXAxis /><HeatmapYAxis tickFilter=\"all\" labelFormat=\"initial\" /><HeatmapTooltip /></HeatmapChart><HeatmapLegend variant=\"gradient\" /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }\n\nexport default function Example() { return <QuartersDemo />; }\n";
const sizingCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction SizingDemo() { return <div className=\"w-full space-y-4\"><div className=\"h-44\"><HeatmapChart data={data.slice(0,26)} layout=\"fill\"><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div><div className=\"overflow-x-auto\"><HeatmapChart data={data.slice(0,12)} binSize={15}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div></div>; }\n\nexport default function Example() { return <SizingDemo />; }\n";
const patternsCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction PatternsDemo() { const styles = HEATMAP_DEFAULT_LEVEL_COLORS.map((color,index) => ({color,fillMode:index > 0 ? \"pattern\" : \"solid\",pattern:\"diagonal\"})) as unknown as HeatmapLevelStyles; return <HeatmapInteractionProvider><HeatmapInteractionBoundary><HeatmapChart data={data} xDomain={[rangeStart,rangeEnd]} levelStyles={styles}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart><HeatmapLegend levelStyles={styles} /></HeatmapInteractionBoundary></HeatmapInteractionProvider>; }\n\nexport default function Example() { return <PatternsDemo />; }\n";
const rangeCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction RangeDemo() { const [half, setHalf] = useState(false); return <div className=\"w-full\"><Button size=\"sm\" variant=\"secondary\" onClick={() => setHalf(v => !v)}>Toggle six months</Button><HeatmapChart data={data} xDomain={[rangeStart,half ? new Date(2026,5,30) : rangeEnd]} sizingColumnCount={half ? 27 : 53}><HeatmapCells hideGhostCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div>; }\n\nexport default function Example() { return <RangeDemo />; }\n";
const loadingCode = "\"use client\";\n\nimport { useState } from \"react\";\nimport { HeatmapChart, HeatmapCells, HeatmapXAxis, HeatmapYAxis, HeatmapTooltip, HeatmapLegend, HeatmapSeparator, HeatmapInteractionProvider, HeatmapInteractionBoundary, getHeatmapWeekStartSunday, type HeatmapColumn, type HeatmapLevelStyles, HEATMAP_DEFAULT_LEVEL_COLORS } from \"@/components/ui/heatmap-chart\";\nimport { Button } from \"@/components/ui/button\";\n\nconst rangeStart = new Date(2026, 0, 1);\nconst rangeEnd = new Date(2026, 11, 31);\nconst weekStart = getHeatmapWeekStartSunday(rangeStart);\nconst data: HeatmapColumn[] = Array.from({ length: 53 }, (_, column) => ({ bin: column, bins: Array.from({ length: 7 }, (_, row) => {\n  const date = new Date(weekStart); date.setDate(date.getDate() + column * 7 + row);\n  return { bin: row, date, count: (column * 3 + row * 7) % 9 };\n}) }));\n\n\n\nfunction LoadingDemo() { const [loading, setLoading] = useState(false); const [replay, setReplay] = useState(0); return <div className=\"w-full\"><div className=\"flex flex-wrap gap-2\"><Button size=\"sm\" variant=\"secondary\" onClick={() => setLoading(v => !v)}>Toggle loading</Button><Button size=\"sm\" variant=\"secondary\" onClick={() => setReplay(v => v + 1)}>Replay</Button></div><HeatmapChart data={data} status={loading ? \"loading\" : \"ready\"} loadingLabel=\"Loading activity\" revealSignature={String(replay)}><HeatmapCells /><HeatmapXAxis /><HeatmapYAxis /><HeatmapTooltip /></HeatmapChart></div>; }\n\nexport default function Example() { return <LoadingDemo />; }\n";

import api from "./api.json";

export default function HeatmapChartDoc() {
  const t = useTranslations("heatmapchart");
  return <DocPage title="HeatmapChart" slug="heatmap-chart" installSlug="heatmap-chart chart-primitives button" description={t("description")}>
    <DocSection title={t("application")}><div className="space-y-2 text-body text-fg-muted"><p>{t("applicationDescription")}</p><Link className="rounded-sm text-fg-brand underline underline-offset-4 outline-none focus-visible:ring-1 focus-visible:ring-focus-ring" href="/updates">{t("applicationLink")}</Link></div></DocSection>
    <DocSection title={t("basic") }><figure aria-label={t("basic")} className="min-w-0 w-full"><ComponentPreview code={basicCode} padding="responsive" preservePreview><BasicDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("quarters") }><figure aria-label={t("quarters")} className="min-w-0 w-full"><ComponentPreview code={quartersCode} padding="responsive" preservePreview><QuartersDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("sizing") }><figure aria-label={t("sizing")} className="min-w-0 w-full"><ComponentPreview code={sizingCode} padding="responsive" preservePreview><SizingDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("patterns") }><figure aria-label={t("patterns")} className="min-w-0 w-full"><ComponentPreview code={patternsCode} padding="responsive" preservePreview><PatternsDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("range") }><figure aria-label={t("range")} className="min-w-0 w-full"><ComponentPreview code={rangeCode} padding="responsive" preservePreview><RangeDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("loading") }><figure aria-label={t("loading")} className="min-w-0 w-full"><ComponentPreview code={loadingCode} padding="responsive" preservePreview><LoadingDemo /></ComponentPreview></figure></DocSection>
    <ChartDataTable caption={t("dataCaption")} summary={t("viewData")} columns={["Date","Count"]} rows={data.flatMap(column => column.bins).map((bin,index) => ({id:String(index),label:bin.date.toISOString(),values:[bin.count]}))} />
    <DocSection title={t("behavior")}><div className="space-y-2 text-body text-fg-muted"><p>{t("contract")}</p><p>{t("keyboard")}</p><p>{t("compatibility")}</p></div></DocSection>
    <DocSection title={t("api")}><PropsTable props={api} /></DocSection>
  </DocPage>;
}
