export const blockCatalog = [
  {
    name: "agent-trace-01",
    title: "Agent Trace",
    description: "A turn-aware trace viewer that projects agent messages, tool calls, and results from uploaded JSON.",
    categories: ["application", "agent", "observability"],
    dependencies: ["badge", "button", "detail-list", "@lobehub/icons"],
  },
  {
    name: "agent-session-detail-01",
    title: "Agent Session Detail",
    description: "A session detail workspace with agent navigation, switchable sessions, and an embedded execution trace.",
    categories: ["application", "agent", "details"],
    dependencies: ["agent-trace-01", "badge", "breadcrumb", "button", "dropdown", "input-message", "menu-item", "nav-item", "nav-menu", "page-layout", "sidebar", "sidebar-identity-row"],
  },
  {
    name: "mcp-detail-01",
    title: "MCP 详情",
    description: "An MCP resource detail page with connection generation, safe copy feedback, and a minimal tool test panel.",
    categories: ["application", "details"],
    dependencies: ["page-layout", "breadcrumb", "tabs", "select", "textarea", "input-copy", "inline-notice", "card", "badge", "button"],
  },
  {
    name: "model-detail-01",
    title: "模型详情",
    description: "A model detail page with API-key handoff, runnable code samples, benchmarks, and endpoint information.",
    categories: ["application", "details"],
    dependencies: ["page-layout", "breadcrumb", "tabs", "table", "input-copy", "card", "badge", "button"],
  },
  {
    name: "cluster-environment-detail-01",
    title: "集群环境详情",
    description: "An inspection-report workspace that combines environment context, resource health, and incident follow-up.",
    categories: ["application", "operations"],
    dependencies: ["page-layout", "breadcrumb", "button", "card", "dialog", "dropdown", "kbd", "nav-item", "nav-menu", "sidebar", "sidebar-identity-row", "tabs", "metric-card", "info-item", "resource-status-all-01", "resource-metric-list-01"],
  },
  {
    name: "cluster-environment-list-01",
    title: "集群环境列表",
    description: "A filterable cluster-environment overview with critical, warning, normal, offline, and data-freshness states.",
    categories: ["application", "operations"],
    dependencies: ["page-layout", "tabs", "input", "button", "card", "badge", "dialog", "dropdown", "kbd", "nav-item", "nav-menu", "sidebar", "sidebar-identity-row", "inline-notice"],
  },
  {
    name: "inspection-report-list-01",
    title: "巡检报告列表",
    description: "An inspection report workspace with operations navigation, filters, report status, and contextual actions.",
    categories: ["application", "operations"],
    dependencies: ["page-layout", "sidebar", "nav-menu", "nav-item", "input", "dropdown", "badge", "button"],
  },
  {
    name: "monitoring-alert-list-01",
    title: "监控告警列表",
    description: "A monitoring alert workspace with shared operations navigation, severity filters, resolution history, and contextual actions.",
    categories: ["application", "operations", "monitoring"],
    dependencies: ["page-layout", "sidebar", "nav-menu", "nav-item", "input", "dropdown", "badge", "button", "button-group", "popover"],
  },
  {
    name: "service-management-01",
    title: "服务管理",
    description: "A service workspace with progress, vendor authorizations, and cluster operation history.",
    categories: ["application", "operations", "service"],
    dependencies: ["page-layout", "sidebar", "nav-menu", "nav-item", "data-table", "tabs", "badge", "button", "dialog", "dropdown", "kbd"],
  },
  {
    name: "personal-settings-01",
    title: "个人设置",
    description: "A personal settings workspace for model services, API keys, credentials, profile details, usage, and call logs.",
    categories: ["application", "settings"],
    dependencies: ["app-shell", "top-nav", "page-layout", "nav-menu", "nav-item", "input-group", "table", "field", "badge", "button", "detail-list", "inline-notice", "@lobehub/icons"],
  },
  {
    name: "personal-model-usage-01",
    title: "个人模型用量",
    description: "A standalone personal model workspace with billing analysis, atomic call logs, and answer-level execution traces.",
    categories: ["application", "settings", "analytics"],
    dependencies: ["personal-settings-01"],
  },
  {
    name: "personal-usage-01",
    title: "个人使用情况",
    description: "A standalone personal activity dashboard with contextual read-only settings navigation.",
    categories: ["application", "settings", "analytics"],
    dependencies: ["personal-settings-01"],
  },
  {
    name: "resource-settings-01",
    title: "模型服务设置",
    description: "A standalone model-service settings page with contextual read-only settings navigation.",
    categories: ["application", "settings"],
    dependencies: ["personal-settings-01"],
  },
  {
    name: "model-mcp-marketplace-01",
    slug: "resource-catalog-01",
    title: "模型和 MCP 广场",
    description: "A filterable model and MCP marketplace with page-local navigation, search, and responsive resource cards.",
    categories: ["application", "catalog"],
    dependencies: ["app-shell", "top-nav", "page-layout", "nav-menu", "nav-item", "input", "kbd", "card", "badge", "button", "@lobehub/icons"],
  },
  {
    name: "provider-create-form-01",
    title: "Provider Create Form 1",
    description: "A three-step workflow for provider details, credential verification, model discovery, and per-model availability.",
    categories: ["application", "forms"],
    dependencies: ["field", "input", "textarea", "select", "switch", "stepper", "container", "alert", "badge", "detail-list", "button", "toast", "@lobehub/icons"],
  },
  {
    name: "resource-details-01",
    title: "Resource Details",
    description: "A grouped resource metadata panel with health, configuration, usage, and API compatibility details.",
    categories: ["application", "details"],
    dependencies: ["detail-list", "switch", "badge"],
  },
  {
    name: "resource-list-table-01",
    title: "Resource List Table 1",
    description: "A searchable, selectable resource inventory with status filtering and reusable row actions.",
    categories: ["application", "tables"],
    dependencies: ["data-table", "info-item", "badge", "checkbox", "button", "input-group"],
  },
  {
    name: "resource-metric-list-01",
    title: "Resource Metric List 1",
    description: "A compact resource inventory with status distribution bars for infrastructure health at a glance.",
    categories: ["application", "metrics"],
    dependencies: ["detail-list"],
  },
  {
    name: "resource-status-all-01",
    title: "Resource Status All 1",
    description: "A resource-status summary with a circular distribution, detailed counts, and determinate-state coverage.",
    categories: ["application", "metrics"],
    dependencies: ["card"],
  },
  {
    name: "top-nav-app-shell-01",
    title: "TopNav App Shell",
    description: "A stacked application shell with a centered TopNav and focused content area.",
    categories: ["application", "navigation"],
    dependencies: ["app-shell", "page-layout", "top-nav", "nav-menu", "nav-item"],
  },
  {
    name: "zaiops-operations-01",
    title: "ZAIops Operations",
    description: "An operations workspace recipe with a responsive Sidebar, organization switcher, and grouped navigation.",
    categories: ["application", "operations"],
    dependencies: ["sidebar", "page-layout", "nav-menu", "nav-item"],
  },
  {
    name: "zlrlist",
    title: "ZLR 保护组",
    description: "A ZS Live Recovery protection-group list and detail workspace with site switching, recovery plans, and Chinese pagination.",
    categories: ["application", "operations", "tables"],
    dependencies: ["sidebar", "nav-menu", "nav-item", "tabs", "input-group", "table", "checkbox", "select", "button", "badge", "detail-list"],
  },
] as const;
