export const blockCatalog = [
  {
    name: "provider-create-form-01",
    title: "Provider Create Form 1",
    description: "A three-step workflow for provider details, credential verification, model discovery, and per-model availability.",
    categories: ["application", "forms"],
    dependencies: ["field", "input", "textarea", "select", "switch", "stepper", "container", "alert", "badge", "detail-list", "button", "toast", "@lobehub/icons"],
  },
  {
    name: "resource-details-01",
    title: "Resource Details",
    description: "A grouped resource metadata panel with health, configuration, usage, and API compatibility details.",
    categories: ["application", "details"],
    dependencies: ["detail-list", "switch", "badge"],
  },
  {
    name: "resource-list-table-01",
    title: "Resource List Table 1",
    description: "A searchable, selectable resource inventory with status filtering and reusable row actions.",
    categories: ["application", "tables"],
    dependencies: ["data-table", "info-item", "badge", "checkbox", "button", "input-group"],
  },
  {
    name: "resource-metric-list-01",
    title: "Resource Metric List 1",
    description: "A compact resource inventory with status distribution bars for infrastructure health at a glance.",
    categories: ["application", "metrics"],
    dependencies: ["detail-list"],
  },
  {
    name: "resource-status-all-01",
    title: "Resource Status All 1",
    description: "A resource-status summary with a circular distribution, detailed counts, and determinate-state coverage.",
    categories: ["application", "metrics"],
    dependencies: ["card"],
  },
  {
    name: "top-nav-app-shell-01",
    title: "TopNav App Shell",
    description: "A stacked application shell with a centered TopNav and focused content area.",
    categories: ["application", "navigation"],
    dependencies: ["app-shell", "page-layout", "top-nav", "nav-menu", "nav-item"],
  },
  {
    name: "zaiops-operations-01",
    title: "ZAIops Operations",
    description: "An operations workspace recipe with a responsive Sidebar, organization switcher, and grouped navigation.",
    categories: ["application", "operations"],
    dependencies: ["sidebar", "page-layout", "nav-menu", "nav-item"],
  },
] as const;
