export const blockCatalog = [
  {
    name: "cluster-environment-list-01",
    title: "集群环境列表",
    description: "A filterable cluster-environment overview with critical, warning, normal, offline, and data-freshness states.",
    categories: ["application", "operations"],
    dependencies: ["page-layout", "tabs", "input", "button", "card", "badge"],
  },
  {
    name: "personal-settings-01",
    title: "个人设置",
    description: "A personal settings workspace for model services, API keys, credentials, profile details, and usage.",
    categories: ["application", "settings"],
    dependencies: ["app-shell", "top-nav", "page-layout", "nav-menu", "nav-item", "input-group", "table", "field", "badge", "button", "@lobehub/icons"],
  },
  {
    name: "model-mcp-marketplace-01",
    slug: "resource-catalog-01",
    title: "模型和 MCP 广场",
    description: "A filterable model and MCP marketplace with page-local navigation, search, and responsive resource cards.",
    categories: ["application", "catalog"],
    dependencies: ["app-shell", "top-nav", "page-layout", "nav-menu", "nav-item", "input", "kbd", "card", "badge", "button", "@lobehub/icons"],
  },
  {
    name: "provider-create-form-01",
    title: "Provider Create Form 1",
    description: "A three-step workflow for provider details, credential verification, model discovery, and per-model availability.",
    categories: ["application", "forms"],
    dependencies: ["field", "input", "textarea", "select", "switch", "stepper", "container", "alert", "badge", "detail-list", "button", "toast", "@lobehub/icons"],
  },
  {
    name: "resource-details-01",
    title: "Resource Details",
    description: "A grouped resource metadata panel with health, configuration, usage, and API compatibility details.",
    categories: ["application", "details"],
    dependencies: ["detail-list", "switch", "badge"],
  },
  {
    name: "resource-list-table-01",
    title: "Resource List Table 1",
    description: "A searchable, selectable resource inventory with status filtering and reusable row actions.",
    categories: ["application", "tables"],
    dependencies: ["data-table", "info-item", "badge", "checkbox", "button", "input-group"],
  },
  {
    name: "resource-metric-list-01",
    title: "Resource Metric List 1",
    description: "A compact resource inventory with status distribution bars for infrastructure health at a glance.",
    categories: ["application", "metrics"],
    dependencies: ["detail-list"],
  },
  {
    name: "resource-status-all-01",
    title: "Resource Status All 1",
    description: "A resource-status summary with a circular distribution, detailed counts, and determinate-state coverage.",
    categories: ["application", "metrics"],
    dependencies: ["card"],
  },
  {
    name: "top-nav-app-shell-01",
    title: "TopNav App Shell",
    description: "A stacked application shell with a centered TopNav and focused content area.",
    categories: ["application", "navigation"],
    dependencies: ["app-shell", "page-layout", "top-nav", "nav-menu", "nav-item"],
  },
  {
    name: "zaiops-operations-01",
    title: "ZAIops Operations",
    description: "An operations workspace recipe with a responsive Sidebar, organization switcher, and grouped navigation.",
    categories: ["application", "operations"],
    dependencies: ["sidebar", "page-layout", "nav-menu", "nav-item"],
  },
] as const;
