"use client";

import { useEffect, useState } from "react";
import { LiveLineChart, LiveLine, LiveXAxis, LiveYAxis, type LiveLinePoint } from "@zeron/ui/live-line-chart";
import { Grid, ChartTooltip } from "@zeron/ui/chart-core";
import { Button } from "@zeron/ui/button";
import { ComponentPreview } from "@docs/components/content/ComponentPreview";
import { DocPage, DocSection } from "@docs/components/content/DocPage";
import { PropsTable } from "@docs/components/content/PropsTable";
import { ChartDataTable } from "@zeron/ui/chart-primitives";
import { useTranslations } from "next-intl";



function StreamDemo({windowSecs=30,leading=0,minimal=false}:{windowSecs?:number;leading?:number;minimal?:boolean}) {
  const [data, setData] = useState<LiveLinePoint[]>([]);
  const [value, setValue] = useState(42);
  const [paused, setPaused] = useState(false);
  const [running, setRunning] = useState(true);
  useEffect(() => {
    if (!running) return;
    let step = 0;
    const update = () => { const time = Date.now() / 1000; const next = 42 + Math.sin(step++ / 4) * 9; setValue(next); setData(previous => [...previous.filter(point => point.time >= time - 120),{time,value:next}]); };
    update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer);
  }, [running]);
  return <div className="w-full"><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setPaused(v => !v)}>{paused ? "Resume scrolling" : "Pause scrolling"}</Button><Button size="sm" variant="secondary" onClick={() => setRunning(v => !v)}>{running ? "Stop source" : "Start source"}</Button></div><LiveLineChart data={data} value={value} window={windowSecs} nowOffsetUnits={leading} paused={paused} exaggerate={minimal}><Grid horizontal /><LiveLine dataKey="value" pulse={!minimal} badge={!minimal} fill={!minimal} momentumColors={minimal ? {up:"var(--chart-1)",down:"var(--chart-3)",flat:"var(--chart-2)"} : undefined} /><LiveXAxis /><LiveYAxis /><ChartTooltip showDatePill={false} /></LiveLineChart><ChartDataTable caption="Live samples (Unix seconds)" columns={["Time (s)","Value"]} rows={data.map(point => ({id:String(point.time),label:String(point.time),values:[point.value.toFixed(2)]}))} /></div>;
}

function BasicDemo() { return <StreamDemo />; }

function WindowDemo() { return <StreamDemo windowSecs={60} leading={1} />; }

function StyleDemo() { return <StreamDemo minimal />; }

const basicCode = "\"use client\";\n\nimport { useEffect, useState } from \"react\";\nimport { LiveLineChart, LiveLine, LiveXAxis, LiveYAxis, type LiveLinePoint } from \"@/components/ui/live-line-chart\";\nimport { Grid, ChartTooltip } from \"@/components/ui/chart-core\";\nimport { Button } from \"@/components/ui/button\";\nimport { ChartDataTable } from \"@/components/ui/chart-primitives\";\n\n\n\nfunction StreamDemo({windowSecs=30,leading=0,minimal=false}:{windowSecs?:number;leading?:number;minimal?:boolean}) {\n  const [data, setData] = useState<LiveLinePoint[]>([]);\n  const [value, setValue] = useState(42);\n  const [paused, setPaused] = useState(false);\n  const [running, setRunning] = useState(true);\n  useEffect(() => {\n    if (!running) return;\n    let step = 0;\n    const update = () => { const time = Date.now() / 1000; const next = 42 + Math.sin(step++ / 4) * 9; setValue(next); setData(previous => [...previous.filter(point => point.time >= time - 120),{time,value:next}]); };\n    update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer);\n  }, [running]);\n  return <div className=\"w-full\"><div className=\"flex flex-wrap gap-2\"><Button size=\"sm\" variant=\"secondary\" onClick={() => setPaused(v => !v)}>{paused ? \"Resume scrolling\" : \"Pause scrolling\"}</Button><Button size=\"sm\" variant=\"secondary\" onClick={() => setRunning(v => !v)}>{running ? \"Stop source\" : \"Start source\"}</Button></div><LiveLineChart data={data} value={value} window={windowSecs} nowOffsetUnits={leading} paused={paused} exaggerate={minimal}><Grid horizontal /><LiveLine dataKey=\"value\" pulse={!minimal} badge={!minimal} fill={!minimal} momentumColors={minimal ? {up:\"var(--chart-1)\",down:\"var(--chart-3)\",flat:\"var(--chart-2)\"} : undefined} /><LiveXAxis /><LiveYAxis /><ChartTooltip showDatePill={false} /></LiveLineChart><ChartDataTable caption=\"Live samples (Unix seconds)\" columns={[\"Time (s)\",\"Value\"]} rows={data.map(point => ({id:String(point.time),label:String(point.time),values:[point.value.toFixed(2)]}))} /></div>;\n}\n\nfunction BasicDemo() { return <StreamDemo />; }\n\nexport default function Example() { return <BasicDemo />; }\n";
const windowCode = "\"use client\";\n\nimport { useEffect, useState } from \"react\";\nimport { LiveLineChart, LiveLine, LiveXAxis, LiveYAxis, type LiveLinePoint } from \"@/components/ui/live-line-chart\";\nimport { Grid, ChartTooltip } from \"@/components/ui/chart-core\";\nimport { Button } from \"@/components/ui/button\";\nimport { ChartDataTable } from \"@/components/ui/chart-primitives\";\n\n\n\nfunction StreamDemo({windowSecs=30,leading=0,minimal=false}:{windowSecs?:number;leading?:number;minimal?:boolean}) {\n  const [data, setData] = useState<LiveLinePoint[]>([]);\n  const [value, setValue] = useState(42);\n  const [paused, setPaused] = useState(false);\n  const [running, setRunning] = useState(true);\n  useEffect(() => {\n    if (!running) return;\n    let step = 0;\n    const update = () => { const time = Date.now() / 1000; const next = 42 + Math.sin(step++ / 4) * 9; setValue(next); setData(previous => [...previous.filter(point => point.time >= time - 120),{time,value:next}]); };\n    update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer);\n  }, [running]);\n  return <div className=\"w-full\"><div className=\"flex flex-wrap gap-2\"><Button size=\"sm\" variant=\"secondary\" onClick={() => setPaused(v => !v)}>{paused ? \"Resume scrolling\" : \"Pause scrolling\"}</Button><Button size=\"sm\" variant=\"secondary\" onClick={() => setRunning(v => !v)}>{running ? \"Stop source\" : \"Start source\"}</Button></div><LiveLineChart data={data} value={value} window={windowSecs} nowOffsetUnits={leading} paused={paused} exaggerate={minimal}><Grid horizontal /><LiveLine dataKey=\"value\" pulse={!minimal} badge={!minimal} fill={!minimal} momentumColors={minimal ? {up:\"var(--chart-1)\",down:\"var(--chart-3)\",flat:\"var(--chart-2)\"} : undefined} /><LiveXAxis /><LiveYAxis /><ChartTooltip showDatePill={false} /></LiveLineChart><ChartDataTable caption=\"Live samples (Unix seconds)\" columns={[\"Time (s)\",\"Value\"]} rows={data.map(point => ({id:String(point.time),label:String(point.time),values:[point.value.toFixed(2)]}))} /></div>;\n}\n\nfunction WindowDemo() { return <StreamDemo windowSecs={60} leading={1} />; }\n\nexport default function Example() { return <WindowDemo />; }\n";
const styleCode = "\"use client\";\n\nimport { useEffect, useState } from \"react\";\nimport { LiveLineChart, LiveLine, LiveXAxis, LiveYAxis, type LiveLinePoint } from \"@/components/ui/live-line-chart\";\nimport { Grid, ChartTooltip } from \"@/components/ui/chart-core\";\nimport { Button } from \"@/components/ui/button\";\nimport { ChartDataTable } from \"@/components/ui/chart-primitives\";\n\n\n\nfunction StreamDemo({windowSecs=30,leading=0,minimal=false}:{windowSecs?:number;leading?:number;minimal?:boolean}) {\n  const [data, setData] = useState<LiveLinePoint[]>([]);\n  const [value, setValue] = useState(42);\n  const [paused, setPaused] = useState(false);\n  const [running, setRunning] = useState(true);\n  useEffect(() => {\n    if (!running) return;\n    let step = 0;\n    const update = () => { const time = Date.now() / 1000; const next = 42 + Math.sin(step++ / 4) * 9; setValue(next); setData(previous => [...previous.filter(point => point.time >= time - 120),{time,value:next}]); };\n    update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer);\n  }, [running]);\n  return <div className=\"w-full\"><div className=\"flex flex-wrap gap-2\"><Button size=\"sm\" variant=\"secondary\" onClick={() => setPaused(v => !v)}>{paused ? \"Resume scrolling\" : \"Pause scrolling\"}</Button><Button size=\"sm\" variant=\"secondary\" onClick={() => setRunning(v => !v)}>{running ? \"Stop source\" : \"Start source\"}</Button></div><LiveLineChart data={data} value={value} window={windowSecs} nowOffsetUnits={leading} paused={paused} exaggerate={minimal}><Grid horizontal /><LiveLine dataKey=\"value\" pulse={!minimal} badge={!minimal} fill={!minimal} momentumColors={minimal ? {up:\"var(--chart-1)\",down:\"var(--chart-3)\",flat:\"var(--chart-2)\"} : undefined} /><LiveXAxis /><LiveYAxis /><ChartTooltip showDatePill={false} /></LiveLineChart><ChartDataTable caption=\"Live samples (Unix seconds)\" columns={[\"Time (s)\",\"Value\"]} rows={data.map(point => ({id:String(point.time),label:String(point.time),values:[point.value.toFixed(2)]}))} /></div>;\n}\n\nfunction StyleDemo() { return <StreamDemo minimal />; }\n\nexport default function Example() { return <StyleDemo />; }\n";

import api from "./api.json";

export default function LiveLineChartDoc() {
  const t = useTranslations("livelinechart");
  return <DocPage title="LiveLineChart" slug="live-line-chart" installSlug="live-line-chart chart-primitives button" description={t("description")}>
    <DocSection title={t("basic") }><figure aria-label={t("basic")} className="min-w-0 w-full"><ComponentPreview code={basicCode} padding="responsive" preservePreview><BasicDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("window") }><figure aria-label={t("window")} className="min-w-0 w-full"><ComponentPreview code={windowCode} padding="responsive" preservePreview><WindowDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("style") }><figure aria-label={t("style")} className="min-w-0 w-full"><ComponentPreview code={styleCode} padding="responsive" preservePreview><StyleDemo /></ComponentPreview></figure></DocSection>
    <DocSection title={t("behavior")}><div className="space-y-2 text-body text-fg-muted"><p>{t("contract")}</p><p>{t("keyboard")}</p><p>{t("compatibility")}</p></div></DocSection>
    <DocSection title={t("api")}><PropsTable props={api} /></DocSection>
  </DocPage>;
}
