// Generated by scripts/generate-semantic-tokens.mjs. Do not edit.
export const mergeBorderWidthTokenNames = ["hairline"] as const;
export const mergeMotionDurationTokenNames = ["fast","fast-exit","moderate","moderate-exit","slow","slow-exit"] as const;
