// Generated by scripts/generate-document-routes.mjs.
import { setRequestLocale } from "next-intl/server";
import { assertLocale } from "@/app/_i18n/locale";
import { generateDocMetadata, renderStaticDocPage } from "@docs/server/render-page";

type Props = { params: Promise<{ locale: string }> };

export async function generateMetadata({ params }: Props) {
  const { locale } = await params;
  assertLocale(locale);
  return generateDocMetadata({ locale, collection: "blocks", slug: "security-overview-01" });
}

export default async function DocumentationPage({ params }: Props) {
  const { locale } = await params;
  assertLocale(locale);
  setRequestLocale(locale);
  return renderStaticDocPage({ locale, collection: "blocks", slug: "security-overview-01", loadPage: () => import("@docs/pages/blocks/security-overview-01/page") });
}
